Homework 1
roland162/epam-nodejs-mentoring-program pull request #1
Opened 2022-11-22 11:10 UTC by roland162

2022-11-22 12:56 UTC, danielcsato requested changes
Please add a nodejs specific .gitignore file then we are good

2022-11-22 13:35 UTC, GergelyBajusz approved these changes

2022-11-22 20:49 UTC, roland162 reviewed
fixed

2022-11-23 08:56 UTC, danielcsato approved these changes

2022-11-23 13:18 UTC, merged